server:
  port: ${PORT}

lavalink:
  server:
    password: ${LAVALINK_PASSWORD}
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
    bufferDurationMs: 400
    resamplingQuality: HIGH
    volume: 100
    maxTracks: 10000
    maxTrackLength: 600000
